<?php
return array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'autoincrement' => true,
            'comment' => app::get('sysshop')->_('id'),
            'label' => app::get('sysshop')->_('id'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'type' => array(
            'type' => array(
                'shop' => app::get('syswechat')->_('商户'),
                'platform' => app::get('syswechat')->_('平台'),
            ),
            'required' => true,
            'label' => app::get('syswechat')->_('账户所有者类型'),
            'comment' => app::get('syswechat')->_('账户所有者类型'),
            'in_list' => true,
            'default_in_list' => true,
        ),
         'wechat_type' => array(
            'type' => array(
                'service' => app::get('syswechat')->_('服务号'),
                'subscription' => app::get('syswechat')->_('订阅号'),
            ),
            'label' => app::get('syswechat')->_('微信账户类型'),
            'comment' => app::get('syswechat')->_('微信账户类型'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'title' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('名称'),
            'label' => app::get('sysshop')->_('名称'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'wechat_account' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('微信账号'),
            'label' => app::get('sysshop')->_('微信账号'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'wechat_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('原始Id'),
            'label' => app::get('sysshop')->_('原始Id'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'email' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('登录邮箱'),
            'label' => app::get('sysshop')->_('登录邮箱'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'eid' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('eid'),
            'label' => app::get('sysshop')->_('eid'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'app_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('AppId'),
            'label' => app::get('sysshop')->_('AppId'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'secret' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('AppSecret'),
          //'label' => app::get('sysshop')->_('AppSecret'),
          //'in_list' => true,
          //'default_in_list' => true,
        ),
        'token' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('Token密钥'),
            'label' => app::get('sysshop')->_('Token密钥'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'qrcode' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('二维码图片'),
            'label' => app::get('sysshop')->_('二维码图片'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'aes_key' => array(
            'type' => 'string',
            'comment' => app::get('sysshop')->_('安全模式加密密钥'),
          //'label' => app::get('sysshop')->_('安全模式加密密钥'),
          //'in_list' => true,
          //'default_in_list' => true,
        ),
    ),
    'primary' => 'id',
    'index' => array(
        'ind_eid' => ['columns' => ['eid']],
    ),
    'comment' => app::get('sysshop')->_('店铺登录操作日志表'),
);
